### ISSUE TITLE
Could not find package miladrahimi/phpcrypt in a version matching 4.*

### ISSUE THREAD

**Issue by jtrod** [miladrahimi/phpcrypt#1]
When I run `composer require miladrahimi/phpcrypt "4.*"` I got this error:

```
  [InvalidArgumentException]
  Could not find package miladrahimi/phpcrypt in a version matching 4.*
```

If I just run `composer require miladrahimi/phpcrypt` I get version 3.  

Other than the readme, there is no reference to version 4 here: https://packagist.org/packages/miladrahimi/phpcrypt

**Comment by miladrahimi** [comment]
A new version is released and readme is also updated.
Thanks for your report. I hope it helps you.
